meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: logstash_docker_z1
    templates:
      # run docker daemon
      - {name: docker, release: docker}
      # warm docker image cache from bosh package
      - {name: cfcommunity_logstash_image, release: logstash-docker}
    instances: 1
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 10240

networks: (( merge ))

properties: {}
