meta:
  job_templates: (( merge ))

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: logstash_docker_z1
    templates: (( meta.job_templates ))
    instances: 1
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 10240

networks: (( merge ))
