---
jobs:
- name: resource-image-logstash14
  public: true
  plan:
  - get: boshrelease-image-logstash14
    trigger: true
  - put: docker-image-logstash14
    params:
      build: boshrelease-image-logstash14/images/logstash14

- name: resource-image-logstash15
  public: true
  plan:
  - get: boshrelease-image-logstash15
    trigger: true
  - put: docker-image-logstash15
    params:
      build: boshrelease-image-logstash15/images/logstash15

- name: image-logstash14
  public: true
  serial: true
  plan:
  - aggregate:
    - get: boshrelease
    - get: boshrelease-image-logstash14
      trigger: true
    - get: docker-image-logstash14
      passed: [resource-image-logstash14]
  - task: bump-image-blob
    config:
      platform: linux
      image: docker:///concourse/concourse-ci
      inputs:
      - name: boshrelease
      - name: docker-image-logstash14
      run:
        path: boshrelease/ci/tasks/bump-image-blob.sh
      params:
        aws_access_key_id: {{blobstore-aws-accesss}}
        aws_secret_access_key: {{blobstore-aws-secret}}
        image: docker-image-logstash14
  - put: boshrelease
    params: {repository: bump-image-blob/boshrelease, rebase: true}

- name: image-logstash15
  public: true
  serial: true
  plan:
  - aggregate:
    - get: boshrelease
    - get: boshrelease-image-logstash14
      trigger: true
    - get: docker-image-logstash15
      passed: [resource-image-logstash15]
  - task: bump-image-blob
    config:
      platform: linux
      image: docker:///concourse/concourse-ci
      inputs:
      - name: boshrelease
      - name: docker-image-logstash15
      run:
        path: boshrelease/ci/tasks/bump-image-blob.sh
      params:
        aws_access_key_id: {{blobstore-aws-accesss}}
        aws_secret_access_key: {{blobstore-aws-secret}}
        image: docker-image-logstash15
  - put: boshrelease
    params: {repository: bump-image-blob/boshrelease, rebase: true}


resources:
- name: boshrelease
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/logstash-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}

- name: boshrelease-image-logstash14
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/logstash-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}
    paths: [images/logstash14/*]

- name: boshrelease-image-logstash15
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/logstash-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}
    paths: [images/logstash15/*]

- name: docker-image-logstash14
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: cfcommunity/logstash
    tag: "1.4"

- name: docker-image-logstash15
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: cfcommunity/logstash
    tag: "1.5"
